// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package oapi

// ContactRequest defines model for ContactRequest.
type ContactRequest struct {
	// CaptchaResponse The captcha response of the form.
	CaptchaResponse *string `json:"captcha_response,omitempty"`

	// Company The company of the contact.
	Company *string `json:"company,omitempty"`

	// Email The email address of the contact.
	Email string `json:"email"`

	// FirstName The first name of the contact.
	FirstName string `json:"first_name"`

	// LastName The last name of the contact.
	LastName *string `json:"last_name,omitempty"`

	// Message The message of the contact.
	Message string `json:"message"`

	// Phone The phone number of the contact.
	Phone *string `json:"phone,omitempty"`

	// Subject The subject of the contact.
	Subject *string `json:"subject,omitempty"`
}

// ContactResponse defines model for ContactResponse.
type ContactResponse struct {
	// Status The status of the request.
	Status *string `json:"status,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// DetailedError The detailed error description.
	DetailedError *string `json:"detailed_error,omitempty"`

	// Location The location of the error.
	Location *string `json:"location,omitempty"`

	// Message The error message.
	Message string `json:"message"`

	// StatusCode The status code of the error.
	StatusCode string `json:"status_code"`
}

// Verbose defines model for verbose.
type Verbose = bool

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = Error

// LiveCheckParams defines parameters for LiveCheck.
type LiveCheckParams struct {
	// Verbose Flag to enable verbose response.
	Verbose *Verbose `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// ReadyCheckParams defines parameters for ReadyCheck.
type ReadyCheckParams struct {
	// Verbose Flag to enable verbose response.
	Verbose *Verbose `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// SaveContactJSONRequestBody defines body for SaveContact for application/json ContentType.
type SaveContactJSONRequestBody = ContactRequest
