---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.45.2
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: test
    image: golang:1.18
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      repo: registry.megpoid.xyz/codestation/goapp
      tags: latest
      buildkit: true
      platforms:
        - linux/amd64
        - linux/arm64
      registry: registry.megpoid.xyz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
      build_args_from_env:
        - goproxy
      environment:
        goproxy:
          from_secret: goproxy_url

    when:
      event:
        - push
        - tag

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_appkey
      template: |
        {
          "images": [
            "registry.megpoid.xyz/codestation/goapp"
          ]
        }

trigger:
  branch:
    - master
    - testing
